add a test sources root, add hamcrest to the junit4 library definition so that unit tests can run (see https://stackoverflow.com/questions/14539072/java-lang-noclassdeffounderror-org-hamcrest-selfdescribing)